# Generated by Django 5.0.4 on 2024-05-06 11:13

import api_rest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_genre_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api_rest.models.upload_image),
        ),
    ]
